---
title: "Дао Пятачка"
author: "Пятачок"
date: today
lang: ru
format:
  beamer:
    colortheme: seahorse
    fonttheme: structurebold
    highlight: tango
    incremental: false
    theme: Warsaw
    toc: false
    pdf_engine: xelatex
    fig-format: png
    fig-dpi: 200
    mainfont: Arial
    monofont: Courier New
    fontsize: "11pt"
    linkcolor: MediumOrchid
    urlcolor: MediumOrchid
    citecolor: MediumOrchid
    include-in-header:
      text: |
        \newfontfamily{\cyrillicfonttt}{Arial}
        \newfontfamily{\cyrillicfont}{Arial}
        \newfontfamily{\cyrillicfontsf}{Arial}
---

```{r}
#| label: setup
#| include: false
library(tidyverse) # манипуляции с данными и графики
```


## Слайд со списком

Пойти в гости:

* к Винни-Пуху

* к Кролику

* к Иа-Иа

## Пробуем шрифты

Простой текст, *курсив*, **жирный**, ~~зачёркнутый~~ :)


## О пчёлах

Пчёлы бывают:

1. Правильные;
1. Неправильные;
1. Прочие;

По последним сводкам с фронта логарифм двух равен `r log(2)`.

## Табличка

| 4   | 4   | 5  | 5  | 4   |
|-----|-----|----|----|-----|
| 45  |     |    |    |  54 |
| 45  | 54  |    |    |  54 |
|  54 | 54  |    |    |  54 |

## Полезности

[Генератор таблиц](http://tablesgenerator.com)

Воронцов, [Введение в Латех](http://www.ccas.ru/voron/download/voron05latex.pdf)

## График с русским текстом через png

```{r}
#| label: plot-cyr
#| fig-height: 6
#| message: false
qplot(x = rnorm(100))  + xlab("Привет!")
```

## График с формулой

```{r}
#| label: plot-math
#| fig-height: 6
#| message: false
library(latex2exp) # LaTeX-формулы на графиках
qplot(x = rnorm(100)) + xlab(TeX("$x^2+y^2=z^2$"))
```