---
title: "Untitled"
format:
  html: 
    code-block-bg: "#fef"
    code-block-border-left: "#faf"
    highlight-style: breeze
    code-tools:
      source: true
      toggle: true
      caption: none
execute: 
  echo: fenced
---

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
#| label: fig-two-plots
#| fig-cap: "Две диаграммы"
#| fig-subcap: 
#|   - "Первая диаграмма"
#|   - "Вторая диаграмма"
#| layout: [[20], [20]]

hist(mtcars$mpg)
hist(mtcars$disp)
```

```{{r}}
#| label: ols-model

ols <- lm(mpg ~ wt, data = mtcars)
```

You can add options to executable code like this 

```{r}
#| label: leaflet-google
library(leaflet)

leaflet() |>
  addTiles(
    # Спутник
    # urlTemplate = "https://mts1.google.com/vt/lyrs=s&hl=en&src=app&x={x}&y={y}&z={z}&s=G",
    # Карта
    urlTemplate = "http://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga",
    attribution = 'Google'
  ) |>
  addMarkers(lng=37.560826, lat=55.722685, popup="Я разговариваю с вами отсюда")
```

